export { default as Dashboard } from "../Dashboard/Dashboard"
export { default as Transactions } from "../Transactions/Transactions"
export { default as Settings } from "../Settings/Settings"
export { default as Categories } from "../Categories/Categories"
export { default as Add } from "../Add/Add"
export { default as Reports } from "../Reports/Reports"